name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to AL STG
    runs-on: windows-latest
    environment: Staging
    
    steps:
      - uses: actions/checkout@v3
            run:|
            ' git push '
      
