name: "Deploying a CI/CD for .NET sample app using GitHub Actions"

on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: [ self-hosted, Windows, X64 ]


    steps:
    # IIS Deployment
    - name: Deploy to IIS Server
      run: |
        iisreset /stop
        Copy-Item ./* C:\inetpub\test\Hello-World -Recurse -Force
        iisreset /start
    # - name: Curl the website as a smoke test
    #   run: curl http://localhost/

   
